# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cad_import_class
                                 A QGIS plugin
 Import Bulgarian CAD4 files to QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-11
        copyright            : (C) 2023 by Dimitar Baldzhiev
        email                : db@tectonica-b.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cad_import_class class from file cad_import_class.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cad_importer import cad_import_class
    return cad_import_class(iface)
